// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protocol.proto
// Protobuf C++ Version: 6.33.4

#include "protocol.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr SC_REMOVE_OBJECT::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        id_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SC_REMOVE_OBJECT::SC_REMOVE_OBJECT(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(SC_REMOVE_OBJECT_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SC_REMOVE_OBJECTDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SC_REMOVE_OBJECTDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SC_REMOVE_OBJECTDefaultTypeInternal() {}
  union {
    SC_REMOVE_OBJECT _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SC_REMOVE_OBJECTDefaultTypeInternal _SC_REMOVE_OBJECT_default_instance_;

inline constexpr SC_PUT_OBJECT::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        id_{0},
        x_{0},
        y_{0},
        o_type_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SC_PUT_OBJECT::SC_PUT_OBJECT(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(SC_PUT_OBJECT_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SC_PUT_OBJECTDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SC_PUT_OBJECTDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SC_PUT_OBJECTDefaultTypeInternal() {}
  union {
    SC_PUT_OBJECT _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SC_PUT_OBJECTDefaultTypeInternal _SC_PUT_OBJECT_default_instance_;

inline constexpr SC_POS::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        id_{0},
        x_{0},
        move_time_{::int64_t{0}},
        y_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SC_POS::SC_POS(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(SC_POS_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SC_POSDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SC_POSDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SC_POSDefaultTypeInternal() {}
  union {
    SC_POS _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SC_POSDefaultTypeInternal _SC_POS_default_instance_;

inline constexpr SC_LOGIN_OK::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        id_{0},
        x_{0},
        y_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SC_LOGIN_OK::SC_LOGIN_OK(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(SC_LOGIN_OK_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SC_LOGIN_OKDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SC_LOGIN_OKDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SC_LOGIN_OKDefaultTypeInternal() {}
  union {
    SC_LOGIN_OK _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SC_LOGIN_OKDefaultTypeInternal _SC_LOGIN_OK_default_instance_;

inline constexpr CS_MOVE::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        move_time_{::int64_t{0}},
        dir_{static_cast< ::Direction >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR CS_MOVE::CS_MOVE(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(CS_MOVE_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CS_MOVEDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CS_MOVEDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CS_MOVEDefaultTypeInternal() {}
  union {
    CS_MOVE _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CS_MOVEDefaultTypeInternal _CS_MOVE_default_instance_;

inline constexpr CS_LOGIN::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        user_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR CS_LOGIN::CS_LOGIN(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(CS_LOGIN_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CS_LOGINDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CS_LOGINDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CS_LOGINDefaultTypeInternal() {}
  union {
    CS_LOGIN _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CS_LOGINDefaultTypeInternal _CS_LOGIN_default_instance_;
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_protocol_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_protocol_2eproto = nullptr;
const ::uint32_t
    TableStruct_protocol_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::SC_LOGIN_OK, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::SC_LOGIN_OK, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::SC_LOGIN_OK, _impl_.x_),
        PROTOBUF_FIELD_OFFSET(::SC_LOGIN_OK, _impl_.y_),
        0,
        1,
        2,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::SC_POS, _impl_._has_bits_),
        7, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::SC_POS, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::SC_POS, _impl_.x_),
        PROTOBUF_FIELD_OFFSET(::SC_POS, _impl_.y_),
        PROTOBUF_FIELD_OFFSET(::SC_POS, _impl_.move_time_),
        0,
        1,
        3,
        2,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::SC_PUT_OBJECT, _impl_._has_bits_),
        7, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::SC_PUT_OBJECT, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::SC_PUT_OBJECT, _impl_.x_),
        PROTOBUF_FIELD_OFFSET(::SC_PUT_OBJECT, _impl_.y_),
        PROTOBUF_FIELD_OFFSET(::SC_PUT_OBJECT, _impl_.o_type_),
        0,
        1,
        2,
        3,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::SC_REMOVE_OBJECT, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::SC_REMOVE_OBJECT, _impl_.id_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::CS_LOGIN, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::CS_LOGIN, _impl_.user_name_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::CS_MOVE, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::CS_MOVE, _impl_.dir_),
        PROTOBUF_FIELD_OFFSET(::CS_MOVE, _impl_.move_time_),
        1,
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::SC_LOGIN_OK)},
        {9, sizeof(::SC_POS)},
        {20, sizeof(::SC_PUT_OBJECT)},
        {31, sizeof(::SC_REMOVE_OBJECT)},
        {36, sizeof(::CS_LOGIN)},
        {41, sizeof(::CS_MOVE)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::_SC_LOGIN_OK_default_instance_._instance,
    &::_SC_POS_default_instance_._instance,
    &::_SC_PUT_OBJECT_default_instance_._instance,
    &::_SC_REMOVE_OBJECT_default_instance_._instance,
    &::_CS_LOGIN_default_instance_._instance,
    &::_CS_MOVE_default_instance_._instance,
};
const char descriptor_table_protodef_protocol_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\016protocol.proto\"/\n\013SC_LOGIN_OK\022\n\n\002id\030\001 "
    "\001(\005\022\t\n\001x\030\002 \001(\005\022\t\n\001y\030\003 \001(\005\"=\n\006SC_POS\022\n\n\002i"
    "d\030\001 \001(\005\022\t\n\001x\030\002 \001(\005\022\t\n\001y\030\003 \001(\005\022\021\n\tmove_ti"
    "me\030\004 \001(\003\"A\n\rSC_PUT_OBJECT\022\n\n\002id\030\001 \001(\005\022\t\n"
    "\001x\030\002 \001(\005\022\t\n\001y\030\003 \001(\005\022\016\n\006o_type\030\004 \001(\005\"\036\n\020S"
    "C_REMOVE_OBJECT\022\n\n\002id\030\001 \001(\005\"\035\n\010CS_LOGIN\022"
    "\021\n\tuser_name\030\001 \001(\t\"5\n\007CS_MOVE\022\027\n\003dir\030\001 \001"
    "(\0162\n.Direction\022\021\n\tmove_time\030\002 \001(\003*2\n\tDir"
    "ection\022\006\n\002UP\020\000\022\010\n\004DOWN\020\001\022\010\n\004LEFT\020\002\022\t\n\005RI"
    "GHT\020\003b\006proto3"
};
static ::absl::once_flag descriptor_table_protocol_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_protocol_2eproto = {
    false,
    false,
    373,
    descriptor_table_protodef_protocol_2eproto,
    "protocol.proto",
    &descriptor_table_protocol_2eproto_once,
    nullptr,
    0,
    6,
    schemas,
    file_default_instances,
    TableStruct_protocol_2eproto::offsets,
    file_level_enum_descriptors_protocol_2eproto,
    file_level_service_descriptors_protocol_2eproto,
};
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Direction_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_protocol_2eproto);
  return file_level_enum_descriptors_protocol_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t Direction_internal_data_[] = {
    262144u, 0u, };
// ===================================================================

class SC_LOGIN_OK::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<SC_LOGIN_OK>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(SC_LOGIN_OK, _impl_._has_bits_);
};

SC_LOGIN_OK::SC_LOGIN_OK(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SC_LOGIN_OK_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:SC_LOGIN_OK)
}
SC_LOGIN_OK::SC_LOGIN_OK(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const SC_LOGIN_OK& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SC_LOGIN_OK_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE SC_LOGIN_OK::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void SC_LOGIN_OK::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, id_),
           0,
           offsetof(Impl_, y_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::y_));
}
SC_LOGIN_OK::~SC_LOGIN_OK() {
  // @@protoc_insertion_point(destructor:SC_LOGIN_OK)
  SharedDtor(*this);
}
inline void SC_LOGIN_OK::SharedDtor(MessageLite& self) {
  SC_LOGIN_OK& this_ = static_cast<SC_LOGIN_OK&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL SC_LOGIN_OK::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) SC_LOGIN_OK(arena);
}
constexpr auto SC_LOGIN_OK::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(SC_LOGIN_OK),
                                            alignof(SC_LOGIN_OK));
}
constexpr auto SC_LOGIN_OK::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_SC_LOGIN_OK_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &SC_LOGIN_OK::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<SC_LOGIN_OK>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &SC_LOGIN_OK::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<SC_LOGIN_OK>(), &SC_LOGIN_OK::ByteSizeLong,
              &SC_LOGIN_OK::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(SC_LOGIN_OK, _impl_._cached_size_),
          false,
      },
      &SC_LOGIN_OK::kDescriptorMethods,
      &descriptor_table_protocol_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull SC_LOGIN_OK_class_data_ =
        SC_LOGIN_OK::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SC_LOGIN_OK::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SC_LOGIN_OK_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(SC_LOGIN_OK_class_data_.tc_table);
  return SC_LOGIN_OK_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2>
SC_LOGIN_OK::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(SC_LOGIN_OK, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    SC_LOGIN_OK_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::SC_LOGIN_OK>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SC_LOGIN_OK, _impl_.id_), 0>(),
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(SC_LOGIN_OK, _impl_.id_)}},
    // int32 x = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SC_LOGIN_OK, _impl_.x_), 1>(),
     {16, 1, 0,
      PROTOBUF_FIELD_OFFSET(SC_LOGIN_OK, _impl_.x_)}},
    // int32 y = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SC_LOGIN_OK, _impl_.y_), 2>(),
     {24, 2, 0,
      PROTOBUF_FIELD_OFFSET(SC_LOGIN_OK, _impl_.y_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 id = 1;
    {PROTOBUF_FIELD_OFFSET(SC_LOGIN_OK, _impl_.id_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // int32 x = 2;
    {PROTOBUF_FIELD_OFFSET(SC_LOGIN_OK, _impl_.x_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // int32 y = 3;
    {PROTOBUF_FIELD_OFFSET(SC_LOGIN_OK, _impl_.y_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void SC_LOGIN_OK::Clear() {
// @@protoc_insertion_point(message_clear_start:SC_LOGIN_OK)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    ::memset(&_impl_.id_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.y_) -
        reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.y_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL SC_LOGIN_OK::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const SC_LOGIN_OK& this_ = static_cast<const SC_LOGIN_OK&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL SC_LOGIN_OK::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const SC_LOGIN_OK& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:SC_LOGIN_OK)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // int32 id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (this_._internal_id() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_id(), target);
    }
  }

  // int32 x = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_x() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<2>(
              stream, this_._internal_x(), target);
    }
  }

  // int32 y = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_y() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<3>(
              stream, this_._internal_y(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:SC_LOGIN_OK)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t SC_LOGIN_OK::ByteSizeLong(const MessageLite& base) {
  const SC_LOGIN_OK& this_ = static_cast<const SC_LOGIN_OK&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t SC_LOGIN_OK::ByteSizeLong() const {
  const SC_LOGIN_OK& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:SC_LOGIN_OK)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    // int32 id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (this_._internal_id() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_id());
      }
    }
    // int32 x = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_x() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_x());
      }
    }
    // int32 y = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_y() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_y());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void SC_LOGIN_OK::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<SC_LOGIN_OK*>(&to_msg);
  auto& from = static_cast<const SC_LOGIN_OK&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:SC_LOGIN_OK)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (from._internal_id() != 0) {
        _this->_impl_.id_ = from._impl_.id_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_x() != 0) {
        _this->_impl_.x_ = from._impl_.x_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_y() != 0) {
        _this->_impl_.y_ = from._impl_.y_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void SC_LOGIN_OK::CopyFrom(const SC_LOGIN_OK& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:SC_LOGIN_OK)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SC_LOGIN_OK::InternalSwap(SC_LOGIN_OK* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SC_LOGIN_OK, _impl_.y_)
      + sizeof(SC_LOGIN_OK::_impl_.y_)
      - PROTOBUF_FIELD_OFFSET(SC_LOGIN_OK, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
}

::google::protobuf::Metadata SC_LOGIN_OK::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class SC_POS::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<SC_POS>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(SC_POS, _impl_._has_bits_);
};

SC_POS::SC_POS(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SC_POS_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:SC_POS)
}
SC_POS::SC_POS(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const SC_POS& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SC_POS_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE SC_POS::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void SC_POS::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, id_),
           0,
           offsetof(Impl_, y_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::y_));
}
SC_POS::~SC_POS() {
  // @@protoc_insertion_point(destructor:SC_POS)
  SharedDtor(*this);
}
inline void SC_POS::SharedDtor(MessageLite& self) {
  SC_POS& this_ = static_cast<SC_POS&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL SC_POS::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) SC_POS(arena);
}
constexpr auto SC_POS::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(SC_POS),
                                            alignof(SC_POS));
}
constexpr auto SC_POS::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_SC_POS_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &SC_POS::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<SC_POS>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &SC_POS::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<SC_POS>(), &SC_POS::ByteSizeLong,
              &SC_POS::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(SC_POS, _impl_._cached_size_),
          false,
      },
      &SC_POS::kDescriptorMethods,
      &descriptor_table_protocol_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull SC_POS_class_data_ =
        SC_POS::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SC_POS::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SC_POS_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(SC_POS_class_data_.tc_table);
  return SC_POS_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 0, 2>
SC_POS::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(SC_POS, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    SC_POS_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::SC_POS>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int64 move_time = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(SC_POS, _impl_.move_time_), 2>(),
     {32, 2, 0,
      PROTOBUF_FIELD_OFFSET(SC_POS, _impl_.move_time_)}},
    // int32 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SC_POS, _impl_.id_), 0>(),
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(SC_POS, _impl_.id_)}},
    // int32 x = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SC_POS, _impl_.x_), 1>(),
     {16, 1, 0,
      PROTOBUF_FIELD_OFFSET(SC_POS, _impl_.x_)}},
    // int32 y = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SC_POS, _impl_.y_), 3>(),
     {24, 3, 0,
      PROTOBUF_FIELD_OFFSET(SC_POS, _impl_.y_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 id = 1;
    {PROTOBUF_FIELD_OFFSET(SC_POS, _impl_.id_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // int32 x = 2;
    {PROTOBUF_FIELD_OFFSET(SC_POS, _impl_.x_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // int32 y = 3;
    {PROTOBUF_FIELD_OFFSET(SC_POS, _impl_.y_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // int64 move_time = 4;
    {PROTOBUF_FIELD_OFFSET(SC_POS, _impl_.move_time_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void SC_POS::Clear() {
// @@protoc_insertion_point(message_clear_start:SC_POS)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    ::memset(&_impl_.id_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.y_) -
        reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.y_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL SC_POS::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const SC_POS& this_ = static_cast<const SC_POS&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL SC_POS::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const SC_POS& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:SC_POS)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // int32 id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (this_._internal_id() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_id(), target);
    }
  }

  // int32 x = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_x() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<2>(
              stream, this_._internal_x(), target);
    }
  }

  // int32 y = 3;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_y() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<3>(
              stream, this_._internal_y(), target);
    }
  }

  // int64 move_time = 4;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_move_time() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<4>(
              stream, this_._internal_move_time(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:SC_POS)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t SC_POS::ByteSizeLong(const MessageLite& base) {
  const SC_POS& this_ = static_cast<const SC_POS&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t SC_POS::ByteSizeLong() const {
  const SC_POS& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:SC_POS)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    // int32 id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (this_._internal_id() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_id());
      }
    }
    // int32 x = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_x() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_x());
      }
    }
    // int64 move_time = 4;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_move_time() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_move_time());
      }
    }
    // int32 y = 3;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_y() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_y());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void SC_POS::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<SC_POS*>(&to_msg);
  auto& from = static_cast<const SC_POS&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:SC_POS)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (from._internal_id() != 0) {
        _this->_impl_.id_ = from._impl_.id_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_x() != 0) {
        _this->_impl_.x_ = from._impl_.x_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_move_time() != 0) {
        _this->_impl_.move_time_ = from._impl_.move_time_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_y() != 0) {
        _this->_impl_.y_ = from._impl_.y_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void SC_POS::CopyFrom(const SC_POS& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:SC_POS)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SC_POS::InternalSwap(SC_POS* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SC_POS, _impl_.y_)
      + sizeof(SC_POS::_impl_.y_)
      - PROTOBUF_FIELD_OFFSET(SC_POS, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
}

::google::protobuf::Metadata SC_POS::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class SC_PUT_OBJECT::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<SC_PUT_OBJECT>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(SC_PUT_OBJECT, _impl_._has_bits_);
};

SC_PUT_OBJECT::SC_PUT_OBJECT(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SC_PUT_OBJECT_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:SC_PUT_OBJECT)
}
SC_PUT_OBJECT::SC_PUT_OBJECT(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const SC_PUT_OBJECT& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SC_PUT_OBJECT_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE SC_PUT_OBJECT::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void SC_PUT_OBJECT::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, id_),
           0,
           offsetof(Impl_, o_type_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::o_type_));
}
SC_PUT_OBJECT::~SC_PUT_OBJECT() {
  // @@protoc_insertion_point(destructor:SC_PUT_OBJECT)
  SharedDtor(*this);
}
inline void SC_PUT_OBJECT::SharedDtor(MessageLite& self) {
  SC_PUT_OBJECT& this_ = static_cast<SC_PUT_OBJECT&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL SC_PUT_OBJECT::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) SC_PUT_OBJECT(arena);
}
constexpr auto SC_PUT_OBJECT::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(SC_PUT_OBJECT),
                                            alignof(SC_PUT_OBJECT));
}
constexpr auto SC_PUT_OBJECT::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_SC_PUT_OBJECT_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &SC_PUT_OBJECT::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<SC_PUT_OBJECT>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &SC_PUT_OBJECT::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<SC_PUT_OBJECT>(), &SC_PUT_OBJECT::ByteSizeLong,
              &SC_PUT_OBJECT::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(SC_PUT_OBJECT, _impl_._cached_size_),
          false,
      },
      &SC_PUT_OBJECT::kDescriptorMethods,
      &descriptor_table_protocol_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull SC_PUT_OBJECT_class_data_ =
        SC_PUT_OBJECT::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SC_PUT_OBJECT::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SC_PUT_OBJECT_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(SC_PUT_OBJECT_class_data_.tc_table);
  return SC_PUT_OBJECT_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 0, 2>
SC_PUT_OBJECT::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(SC_PUT_OBJECT, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    SC_PUT_OBJECT_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::SC_PUT_OBJECT>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 o_type = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SC_PUT_OBJECT, _impl_.o_type_), 3>(),
     {32, 3, 0,
      PROTOBUF_FIELD_OFFSET(SC_PUT_OBJECT, _impl_.o_type_)}},
    // int32 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SC_PUT_OBJECT, _impl_.id_), 0>(),
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(SC_PUT_OBJECT, _impl_.id_)}},
    // int32 x = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SC_PUT_OBJECT, _impl_.x_), 1>(),
     {16, 1, 0,
      PROTOBUF_FIELD_OFFSET(SC_PUT_OBJECT, _impl_.x_)}},
    // int32 y = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SC_PUT_OBJECT, _impl_.y_), 2>(),
     {24, 2, 0,
      PROTOBUF_FIELD_OFFSET(SC_PUT_OBJECT, _impl_.y_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 id = 1;
    {PROTOBUF_FIELD_OFFSET(SC_PUT_OBJECT, _impl_.id_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // int32 x = 2;
    {PROTOBUF_FIELD_OFFSET(SC_PUT_OBJECT, _impl_.x_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // int32 y = 3;
    {PROTOBUF_FIELD_OFFSET(SC_PUT_OBJECT, _impl_.y_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // int32 o_type = 4;
    {PROTOBUF_FIELD_OFFSET(SC_PUT_OBJECT, _impl_.o_type_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void SC_PUT_OBJECT::Clear() {
// @@protoc_insertion_point(message_clear_start:SC_PUT_OBJECT)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    ::memset(&_impl_.id_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.o_type_) -
        reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.o_type_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL SC_PUT_OBJECT::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const SC_PUT_OBJECT& this_ = static_cast<const SC_PUT_OBJECT&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL SC_PUT_OBJECT::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const SC_PUT_OBJECT& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:SC_PUT_OBJECT)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // int32 id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (this_._internal_id() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_id(), target);
    }
  }

  // int32 x = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_x() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<2>(
              stream, this_._internal_x(), target);
    }
  }

  // int32 y = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_y() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<3>(
              stream, this_._internal_y(), target);
    }
  }

  // int32 o_type = 4;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_o_type() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<4>(
              stream, this_._internal_o_type(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:SC_PUT_OBJECT)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t SC_PUT_OBJECT::ByteSizeLong(const MessageLite& base) {
  const SC_PUT_OBJECT& this_ = static_cast<const SC_PUT_OBJECT&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t SC_PUT_OBJECT::ByteSizeLong() const {
  const SC_PUT_OBJECT& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:SC_PUT_OBJECT)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    // int32 id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (this_._internal_id() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_id());
      }
    }
    // int32 x = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_x() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_x());
      }
    }
    // int32 y = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_y() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_y());
      }
    }
    // int32 o_type = 4;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_o_type() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_o_type());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void SC_PUT_OBJECT::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<SC_PUT_OBJECT*>(&to_msg);
  auto& from = static_cast<const SC_PUT_OBJECT&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:SC_PUT_OBJECT)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (from._internal_id() != 0) {
        _this->_impl_.id_ = from._impl_.id_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_x() != 0) {
        _this->_impl_.x_ = from._impl_.x_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_y() != 0) {
        _this->_impl_.y_ = from._impl_.y_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_o_type() != 0) {
        _this->_impl_.o_type_ = from._impl_.o_type_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void SC_PUT_OBJECT::CopyFrom(const SC_PUT_OBJECT& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:SC_PUT_OBJECT)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SC_PUT_OBJECT::InternalSwap(SC_PUT_OBJECT* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SC_PUT_OBJECT, _impl_.o_type_)
      + sizeof(SC_PUT_OBJECT::_impl_.o_type_)
      - PROTOBUF_FIELD_OFFSET(SC_PUT_OBJECT, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
}

::google::protobuf::Metadata SC_PUT_OBJECT::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class SC_REMOVE_OBJECT::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<SC_REMOVE_OBJECT>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(SC_REMOVE_OBJECT, _impl_._has_bits_);
};

SC_REMOVE_OBJECT::SC_REMOVE_OBJECT(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SC_REMOVE_OBJECT_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:SC_REMOVE_OBJECT)
}
SC_REMOVE_OBJECT::SC_REMOVE_OBJECT(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const SC_REMOVE_OBJECT& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SC_REMOVE_OBJECT_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE SC_REMOVE_OBJECT::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void SC_REMOVE_OBJECT::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.id_ = {};
}
SC_REMOVE_OBJECT::~SC_REMOVE_OBJECT() {
  // @@protoc_insertion_point(destructor:SC_REMOVE_OBJECT)
  SharedDtor(*this);
}
inline void SC_REMOVE_OBJECT::SharedDtor(MessageLite& self) {
  SC_REMOVE_OBJECT& this_ = static_cast<SC_REMOVE_OBJECT&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL SC_REMOVE_OBJECT::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) SC_REMOVE_OBJECT(arena);
}
constexpr auto SC_REMOVE_OBJECT::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(SC_REMOVE_OBJECT),
                                            alignof(SC_REMOVE_OBJECT));
}
constexpr auto SC_REMOVE_OBJECT::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_SC_REMOVE_OBJECT_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &SC_REMOVE_OBJECT::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<SC_REMOVE_OBJECT>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &SC_REMOVE_OBJECT::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<SC_REMOVE_OBJECT>(), &SC_REMOVE_OBJECT::ByteSizeLong,
              &SC_REMOVE_OBJECT::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(SC_REMOVE_OBJECT, _impl_._cached_size_),
          false,
      },
      &SC_REMOVE_OBJECT::kDescriptorMethods,
      &descriptor_table_protocol_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull SC_REMOVE_OBJECT_class_data_ =
        SC_REMOVE_OBJECT::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SC_REMOVE_OBJECT::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SC_REMOVE_OBJECT_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(SC_REMOVE_OBJECT_class_data_.tc_table);
  return SC_REMOVE_OBJECT_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
SC_REMOVE_OBJECT::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(SC_REMOVE_OBJECT, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    SC_REMOVE_OBJECT_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::SC_REMOVE_OBJECT>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SC_REMOVE_OBJECT, _impl_.id_), 0>(),
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(SC_REMOVE_OBJECT, _impl_.id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 id = 1;
    {PROTOBUF_FIELD_OFFSET(SC_REMOVE_OBJECT, _impl_.id_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void SC_REMOVE_OBJECT::Clear() {
// @@protoc_insertion_point(message_clear_start:SC_REMOVE_OBJECT)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.id_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL SC_REMOVE_OBJECT::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const SC_REMOVE_OBJECT& this_ = static_cast<const SC_REMOVE_OBJECT&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL SC_REMOVE_OBJECT::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const SC_REMOVE_OBJECT& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:SC_REMOVE_OBJECT)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // int32 id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (this_._internal_id() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_id(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:SC_REMOVE_OBJECT)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t SC_REMOVE_OBJECT::ByteSizeLong(const MessageLite& base) {
  const SC_REMOVE_OBJECT& this_ = static_cast<const SC_REMOVE_OBJECT&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t SC_REMOVE_OBJECT::ByteSizeLong() const {
  const SC_REMOVE_OBJECT& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:SC_REMOVE_OBJECT)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // int32 id = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (this_._internal_id() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_id());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void SC_REMOVE_OBJECT::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<SC_REMOVE_OBJECT*>(&to_msg);
  auto& from = static_cast<const SC_REMOVE_OBJECT&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:SC_REMOVE_OBJECT)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (from._internal_id() != 0) {
      _this->_impl_.id_ = from._impl_.id_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void SC_REMOVE_OBJECT::CopyFrom(const SC_REMOVE_OBJECT& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:SC_REMOVE_OBJECT)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SC_REMOVE_OBJECT::InternalSwap(SC_REMOVE_OBJECT* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.id_, other->_impl_.id_);
}

::google::protobuf::Metadata SC_REMOVE_OBJECT::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CS_LOGIN::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<CS_LOGIN>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CS_LOGIN, _impl_._has_bits_);
};

CS_LOGIN::CS_LOGIN(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CS_LOGIN_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:CS_LOGIN)
}
PROTOBUF_NDEBUG_INLINE CS_LOGIN::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::CS_LOGIN& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        user_name_(arena, from.user_name_) {}

CS_LOGIN::CS_LOGIN(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const CS_LOGIN& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CS_LOGIN_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CS_LOGIN* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:CS_LOGIN)
}
PROTOBUF_NDEBUG_INLINE CS_LOGIN::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        user_name_(arena) {}

inline void CS_LOGIN::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
CS_LOGIN::~CS_LOGIN() {
  // @@protoc_insertion_point(destructor:CS_LOGIN)
  SharedDtor(*this);
}
inline void CS_LOGIN::SharedDtor(MessageLite& self) {
  CS_LOGIN& this_ = static_cast<CS_LOGIN&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.user_name_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL CS_LOGIN::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CS_LOGIN(arena);
}
constexpr auto CS_LOGIN::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(CS_LOGIN),
                                            alignof(CS_LOGIN));
}
constexpr auto CS_LOGIN::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CS_LOGIN_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &CS_LOGIN::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CS_LOGIN>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CS_LOGIN::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<CS_LOGIN>(), &CS_LOGIN::ByteSizeLong,
              &CS_LOGIN::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CS_LOGIN, _impl_._cached_size_),
          false,
      },
      &CS_LOGIN::kDescriptorMethods,
      &descriptor_table_protocol_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CS_LOGIN_class_data_ =
        CS_LOGIN::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CS_LOGIN::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CS_LOGIN_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CS_LOGIN_class_data_.tc_table);
  return CS_LOGIN_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 26, 2>
CS_LOGIN::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CS_LOGIN, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    CS_LOGIN_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::CS_LOGIN>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string user_name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(CS_LOGIN, _impl_.user_name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string user_name = 1;
    {PROTOBUF_FIELD_OFFSET(CS_LOGIN, _impl_.user_name_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\10\11\0\0\0\0\0\0"
    "CS_LOGIN"
    "user_name"
  }},
};
PROTOBUF_NOINLINE void CS_LOGIN::Clear() {
// @@protoc_insertion_point(message_clear_start:CS_LOGIN)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.user_name_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL CS_LOGIN::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const CS_LOGIN& this_ = static_cast<const CS_LOGIN&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL CS_LOGIN::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const CS_LOGIN& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:CS_LOGIN)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string user_name = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_user_name().empty()) {
      const ::std::string& _s = this_._internal_user_name();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "CS_LOGIN.user_name");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CS_LOGIN)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t CS_LOGIN::ByteSizeLong(const MessageLite& base) {
  const CS_LOGIN& this_ = static_cast<const CS_LOGIN&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t CS_LOGIN::ByteSizeLong() const {
  const CS_LOGIN& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:CS_LOGIN)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // string user_name = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_user_name().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_user_name());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void CS_LOGIN::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<CS_LOGIN*>(&to_msg);
  auto& from = static_cast<const CS_LOGIN&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:CS_LOGIN)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!from._internal_user_name().empty()) {
      _this->_internal_set_user_name(from._internal_user_name());
    } else {
      if (_this->_impl_.user_name_.IsDefault()) {
        _this->_internal_set_user_name("");
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void CS_LOGIN::CopyFrom(const CS_LOGIN& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:CS_LOGIN)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CS_LOGIN::InternalSwap(CS_LOGIN* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.user_name_, &other->_impl_.user_name_, arena);
}

::google::protobuf::Metadata CS_LOGIN::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CS_MOVE::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<CS_MOVE>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CS_MOVE, _impl_._has_bits_);
};

CS_MOVE::CS_MOVE(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CS_MOVE_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:CS_MOVE)
}
CS_MOVE::CS_MOVE(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CS_MOVE& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CS_MOVE_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE CS_MOVE::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void CS_MOVE::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, move_time_),
           0,
           offsetof(Impl_, dir_) -
               offsetof(Impl_, move_time_) +
               sizeof(Impl_::dir_));
}
CS_MOVE::~CS_MOVE() {
  // @@protoc_insertion_point(destructor:CS_MOVE)
  SharedDtor(*this);
}
inline void CS_MOVE::SharedDtor(MessageLite& self) {
  CS_MOVE& this_ = static_cast<CS_MOVE&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL CS_MOVE::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CS_MOVE(arena);
}
constexpr auto CS_MOVE::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(CS_MOVE),
                                            alignof(CS_MOVE));
}
constexpr auto CS_MOVE::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CS_MOVE_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &CS_MOVE::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CS_MOVE>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CS_MOVE::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<CS_MOVE>(), &CS_MOVE::ByteSizeLong,
              &CS_MOVE::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CS_MOVE, _impl_._cached_size_),
          false,
      },
      &CS_MOVE::kDescriptorMethods,
      &descriptor_table_protocol_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CS_MOVE_class_data_ =
        CS_MOVE::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CS_MOVE::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CS_MOVE_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CS_MOVE_class_data_.tc_table);
  return CS_MOVE_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2>
CS_MOVE::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CS_MOVE, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    CS_MOVE_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::CS_MOVE>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int64 move_time = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(CS_MOVE, _impl_.move_time_), 0>(),
     {16, 0, 0,
      PROTOBUF_FIELD_OFFSET(CS_MOVE, _impl_.move_time_)}},
    // .Direction dir = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CS_MOVE, _impl_.dir_), 1>(),
     {8, 1, 0,
      PROTOBUF_FIELD_OFFSET(CS_MOVE, _impl_.dir_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .Direction dir = 1;
    {PROTOBUF_FIELD_OFFSET(CS_MOVE, _impl_.dir_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // int64 move_time = 2;
    {PROTOBUF_FIELD_OFFSET(CS_MOVE, _impl_.move_time_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void CS_MOVE::Clear() {
// @@protoc_insertion_point(message_clear_start:CS_MOVE)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    ::memset(&_impl_.move_time_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.dir_) -
        reinterpret_cast<char*>(&_impl_.move_time_)) + sizeof(_impl_.dir_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL CS_MOVE::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const CS_MOVE& this_ = static_cast<const CS_MOVE&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL CS_MOVE::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const CS_MOVE& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:CS_MOVE)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .Direction dir = 1;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_dir() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          1, this_._internal_dir(), target);
    }
  }

  // int64 move_time = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (this_._internal_move_time() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<2>(
              stream, this_._internal_move_time(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CS_MOVE)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t CS_MOVE::ByteSizeLong(const MessageLite& base) {
  const CS_MOVE& this_ = static_cast<const CS_MOVE&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t CS_MOVE::ByteSizeLong() const {
  const CS_MOVE& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:CS_MOVE)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // int64 move_time = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (this_._internal_move_time() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_move_time());
      }
    }
    // .Direction dir = 1;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_dir() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_dir());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void CS_MOVE::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<CS_MOVE*>(&to_msg);
  auto& from = static_cast<const CS_MOVE&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:CS_MOVE)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (from._internal_move_time() != 0) {
        _this->_impl_.move_time_ = from._impl_.move_time_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_dir() != 0) {
        _this->_impl_.dir_ = from._impl_.dir_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void CS_MOVE::CopyFrom(const CS_MOVE& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:CS_MOVE)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CS_MOVE::InternalSwap(CS_MOVE* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CS_MOVE, _impl_.dir_)
      + sizeof(CS_MOVE::_impl_.dir_)
      - PROTOBUF_FIELD_OFFSET(CS_MOVE, _impl_.move_time_)>(
          reinterpret_cast<char*>(&_impl_.move_time_),
          reinterpret_cast<char*>(&other->_impl_.move_time_));
}

::google::protobuf::Metadata CS_MOVE::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_protocol_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
