// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protocol.proto
// Protobuf C++ Version: 6.33.4

#ifndef protocol_2eproto_2epb_2eh
#define protocol_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_protocol_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_protocol_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_protocol_2eproto;
}  // extern "C"
enum Direction : int;
extern const uint32_t Direction_internal_data_[];
class CS_LOGIN;
struct CS_LOGINDefaultTypeInternal;
extern CS_LOGINDefaultTypeInternal _CS_LOGIN_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CS_LOGIN_class_data_;
class CS_MOVE;
struct CS_MOVEDefaultTypeInternal;
extern CS_MOVEDefaultTypeInternal _CS_MOVE_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CS_MOVE_class_data_;
class SC_LOGIN_OK;
struct SC_LOGIN_OKDefaultTypeInternal;
extern SC_LOGIN_OKDefaultTypeInternal _SC_LOGIN_OK_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull SC_LOGIN_OK_class_data_;
class SC_POS;
struct SC_POSDefaultTypeInternal;
extern SC_POSDefaultTypeInternal _SC_POS_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull SC_POS_class_data_;
class SC_PUT_OBJECT;
struct SC_PUT_OBJECTDefaultTypeInternal;
extern SC_PUT_OBJECTDefaultTypeInternal _SC_PUT_OBJECT_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull SC_PUT_OBJECT_class_data_;
class SC_REMOVE_OBJECT;
struct SC_REMOVE_OBJECTDefaultTypeInternal;
extern SC_REMOVE_OBJECTDefaultTypeInternal _SC_REMOVE_OBJECT_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull SC_REMOVE_OBJECT_class_data_;
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::Direction_internal_data_>
    internal::EnumTraitsImpl::value<::Direction>;
}  // namespace protobuf
}  // namespace google

enum Direction : int {
  UP = 0,
  DOWN = 1,
  LEFT = 2,
  RIGHT = 3,
  Direction_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  Direction_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t Direction_internal_data_[];
inline constexpr Direction Direction_MIN =
    static_cast<Direction>(0);
inline constexpr Direction Direction_MAX =
    static_cast<Direction>(3);
inline bool Direction_IsValid(int value) {
  return 0 <= value && value <= 3;
}
inline constexpr int Direction_ARRAYSIZE = 3 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Direction_descriptor();
template <typename T>
const ::std::string& Direction_Name(T value) {
  static_assert(::std::is_same<T, Direction>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to Direction_Name().");
  return Direction_Name(static_cast<Direction>(value));
}
template <>
inline const ::std::string& Direction_Name(Direction value) {
  return ::google::protobuf::internal::NameOfDenseEnum<Direction_descriptor, 0, 3>(
      static_cast<int>(value));
}
inline bool Direction_Parse(
    ::absl::string_view name, Direction* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<Direction>(Direction_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class SC_REMOVE_OBJECT final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:SC_REMOVE_OBJECT) */ {
 public:
  inline SC_REMOVE_OBJECT() : SC_REMOVE_OBJECT(nullptr) {}
  ~SC_REMOVE_OBJECT() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SC_REMOVE_OBJECT* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SC_REMOVE_OBJECT));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SC_REMOVE_OBJECT(::google::protobuf::internal::ConstantInitialized);

  inline SC_REMOVE_OBJECT(const SC_REMOVE_OBJECT& from) : SC_REMOVE_OBJECT(nullptr, from) {}
  inline SC_REMOVE_OBJECT(SC_REMOVE_OBJECT&& from) noexcept
      : SC_REMOVE_OBJECT(nullptr, ::std::move(from)) {}
  inline SC_REMOVE_OBJECT& operator=(const SC_REMOVE_OBJECT& from) {
    CopyFrom(from);
    return *this;
  }
  inline SC_REMOVE_OBJECT& operator=(SC_REMOVE_OBJECT&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SC_REMOVE_OBJECT& default_instance() {
    return *reinterpret_cast<const SC_REMOVE_OBJECT*>(
        &_SC_REMOVE_OBJECT_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(SC_REMOVE_OBJECT& a, SC_REMOVE_OBJECT& b) { a.Swap(&b); }
  inline void Swap(SC_REMOVE_OBJECT* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SC_REMOVE_OBJECT* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SC_REMOVE_OBJECT* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SC_REMOVE_OBJECT>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SC_REMOVE_OBJECT& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SC_REMOVE_OBJECT& from) { SC_REMOVE_OBJECT::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SC_REMOVE_OBJECT* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "SC_REMOVE_OBJECT"; }

  explicit SC_REMOVE_OBJECT(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  SC_REMOVE_OBJECT(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const SC_REMOVE_OBJECT& from);
  SC_REMOVE_OBJECT(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, SC_REMOVE_OBJECT&& from) noexcept
      : SC_REMOVE_OBJECT(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIdFieldNumber = 1,
  };
  // int32 id = 1;
  void clear_id() ;
  ::int32_t id() const;
  void set_id(::int32_t value);

  private:
  ::int32_t _internal_id() const;
  void _internal_set_id(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:SC_REMOVE_OBJECT)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const SC_REMOVE_OBJECT& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_protocol_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull SC_REMOVE_OBJECT_class_data_;
// -------------------------------------------------------------------

class SC_PUT_OBJECT final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:SC_PUT_OBJECT) */ {
 public:
  inline SC_PUT_OBJECT() : SC_PUT_OBJECT(nullptr) {}
  ~SC_PUT_OBJECT() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SC_PUT_OBJECT* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SC_PUT_OBJECT));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SC_PUT_OBJECT(::google::protobuf::internal::ConstantInitialized);

  inline SC_PUT_OBJECT(const SC_PUT_OBJECT& from) : SC_PUT_OBJECT(nullptr, from) {}
  inline SC_PUT_OBJECT(SC_PUT_OBJECT&& from) noexcept
      : SC_PUT_OBJECT(nullptr, ::std::move(from)) {}
  inline SC_PUT_OBJECT& operator=(const SC_PUT_OBJECT& from) {
    CopyFrom(from);
    return *this;
  }
  inline SC_PUT_OBJECT& operator=(SC_PUT_OBJECT&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SC_PUT_OBJECT& default_instance() {
    return *reinterpret_cast<const SC_PUT_OBJECT*>(
        &_SC_PUT_OBJECT_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(SC_PUT_OBJECT& a, SC_PUT_OBJECT& b) { a.Swap(&b); }
  inline void Swap(SC_PUT_OBJECT* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SC_PUT_OBJECT* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SC_PUT_OBJECT* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SC_PUT_OBJECT>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SC_PUT_OBJECT& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SC_PUT_OBJECT& from) { SC_PUT_OBJECT::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SC_PUT_OBJECT* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "SC_PUT_OBJECT"; }

  explicit SC_PUT_OBJECT(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  SC_PUT_OBJECT(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const SC_PUT_OBJECT& from);
  SC_PUT_OBJECT(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, SC_PUT_OBJECT&& from) noexcept
      : SC_PUT_OBJECT(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIdFieldNumber = 1,
    kXFieldNumber = 2,
    kYFieldNumber = 3,
    kOTypeFieldNumber = 4,
  };
  // int32 id = 1;
  void clear_id() ;
  ::int32_t id() const;
  void set_id(::int32_t value);

  private:
  ::int32_t _internal_id() const;
  void _internal_set_id(::int32_t value);

  public:
  // int32 x = 2;
  void clear_x() ;
  ::int32_t x() const;
  void set_x(::int32_t value);

  private:
  ::int32_t _internal_x() const;
  void _internal_set_x(::int32_t value);

  public:
  // int32 y = 3;
  void clear_y() ;
  ::int32_t y() const;
  void set_y(::int32_t value);

  private:
  ::int32_t _internal_y() const;
  void _internal_set_y(::int32_t value);

  public:
  // int32 o_type = 4;
  void clear_o_type() ;
  ::int32_t o_type() const;
  void set_o_type(::int32_t value);

  private:
  ::int32_t _internal_o_type() const;
  void _internal_set_o_type(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:SC_PUT_OBJECT)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const SC_PUT_OBJECT& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t id_;
    ::int32_t x_;
    ::int32_t y_;
    ::int32_t o_type_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_protocol_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull SC_PUT_OBJECT_class_data_;
// -------------------------------------------------------------------

class SC_POS final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:SC_POS) */ {
 public:
  inline SC_POS() : SC_POS(nullptr) {}
  ~SC_POS() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SC_POS* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SC_POS));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SC_POS(::google::protobuf::internal::ConstantInitialized);

  inline SC_POS(const SC_POS& from) : SC_POS(nullptr, from) {}
  inline SC_POS(SC_POS&& from) noexcept
      : SC_POS(nullptr, ::std::move(from)) {}
  inline SC_POS& operator=(const SC_POS& from) {
    CopyFrom(from);
    return *this;
  }
  inline SC_POS& operator=(SC_POS&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SC_POS& default_instance() {
    return *reinterpret_cast<const SC_POS*>(
        &_SC_POS_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(SC_POS& a, SC_POS& b) { a.Swap(&b); }
  inline void Swap(SC_POS* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SC_POS* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SC_POS* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SC_POS>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SC_POS& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SC_POS& from) { SC_POS::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SC_POS* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "SC_POS"; }

  explicit SC_POS(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  SC_POS(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const SC_POS& from);
  SC_POS(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, SC_POS&& from) noexcept
      : SC_POS(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIdFieldNumber = 1,
    kXFieldNumber = 2,
    kMoveTimeFieldNumber = 4,
    kYFieldNumber = 3,
  };
  // int32 id = 1;
  void clear_id() ;
  ::int32_t id() const;
  void set_id(::int32_t value);

  private:
  ::int32_t _internal_id() const;
  void _internal_set_id(::int32_t value);

  public:
  // int32 x = 2;
  void clear_x() ;
  ::int32_t x() const;
  void set_x(::int32_t value);

  private:
  ::int32_t _internal_x() const;
  void _internal_set_x(::int32_t value);

  public:
  // int64 move_time = 4;
  void clear_move_time() ;
  ::int64_t move_time() const;
  void set_move_time(::int64_t value);

  private:
  ::int64_t _internal_move_time() const;
  void _internal_set_move_time(::int64_t value);

  public:
  // int32 y = 3;
  void clear_y() ;
  ::int32_t y() const;
  void set_y(::int32_t value);

  private:
  ::int32_t _internal_y() const;
  void _internal_set_y(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:SC_POS)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const SC_POS& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t id_;
    ::int32_t x_;
    ::int64_t move_time_;
    ::int32_t y_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_protocol_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull SC_POS_class_data_;
// -------------------------------------------------------------------

class SC_LOGIN_OK final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:SC_LOGIN_OK) */ {
 public:
  inline SC_LOGIN_OK() : SC_LOGIN_OK(nullptr) {}
  ~SC_LOGIN_OK() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SC_LOGIN_OK* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SC_LOGIN_OK));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SC_LOGIN_OK(::google::protobuf::internal::ConstantInitialized);

  inline SC_LOGIN_OK(const SC_LOGIN_OK& from) : SC_LOGIN_OK(nullptr, from) {}
  inline SC_LOGIN_OK(SC_LOGIN_OK&& from) noexcept
      : SC_LOGIN_OK(nullptr, ::std::move(from)) {}
  inline SC_LOGIN_OK& operator=(const SC_LOGIN_OK& from) {
    CopyFrom(from);
    return *this;
  }
  inline SC_LOGIN_OK& operator=(SC_LOGIN_OK&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SC_LOGIN_OK& default_instance() {
    return *reinterpret_cast<const SC_LOGIN_OK*>(
        &_SC_LOGIN_OK_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(SC_LOGIN_OK& a, SC_LOGIN_OK& b) { a.Swap(&b); }
  inline void Swap(SC_LOGIN_OK* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SC_LOGIN_OK* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SC_LOGIN_OK* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SC_LOGIN_OK>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SC_LOGIN_OK& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SC_LOGIN_OK& from) { SC_LOGIN_OK::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SC_LOGIN_OK* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "SC_LOGIN_OK"; }

  explicit SC_LOGIN_OK(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  SC_LOGIN_OK(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const SC_LOGIN_OK& from);
  SC_LOGIN_OK(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, SC_LOGIN_OK&& from) noexcept
      : SC_LOGIN_OK(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIdFieldNumber = 1,
    kXFieldNumber = 2,
    kYFieldNumber = 3,
  };
  // int32 id = 1;
  void clear_id() ;
  ::int32_t id() const;
  void set_id(::int32_t value);

  private:
  ::int32_t _internal_id() const;
  void _internal_set_id(::int32_t value);

  public:
  // int32 x = 2;
  void clear_x() ;
  ::int32_t x() const;
  void set_x(::int32_t value);

  private:
  ::int32_t _internal_x() const;
  void _internal_set_x(::int32_t value);

  public:
  // int32 y = 3;
  void clear_y() ;
  ::int32_t y() const;
  void set_y(::int32_t value);

  private:
  ::int32_t _internal_y() const;
  void _internal_set_y(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:SC_LOGIN_OK)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const SC_LOGIN_OK& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t id_;
    ::int32_t x_;
    ::int32_t y_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_protocol_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull SC_LOGIN_OK_class_data_;
// -------------------------------------------------------------------

class CS_MOVE final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:CS_MOVE) */ {
 public:
  inline CS_MOVE() : CS_MOVE(nullptr) {}
  ~CS_MOVE() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CS_MOVE* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CS_MOVE));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CS_MOVE(::google::protobuf::internal::ConstantInitialized);

  inline CS_MOVE(const CS_MOVE& from) : CS_MOVE(nullptr, from) {}
  inline CS_MOVE(CS_MOVE&& from) noexcept
      : CS_MOVE(nullptr, ::std::move(from)) {}
  inline CS_MOVE& operator=(const CS_MOVE& from) {
    CopyFrom(from);
    return *this;
  }
  inline CS_MOVE& operator=(CS_MOVE&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CS_MOVE& default_instance() {
    return *reinterpret_cast<const CS_MOVE*>(
        &_CS_MOVE_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 5;
  friend void swap(CS_MOVE& a, CS_MOVE& b) { a.Swap(&b); }
  inline void Swap(CS_MOVE* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CS_MOVE* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CS_MOVE* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CS_MOVE>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CS_MOVE& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CS_MOVE& from) { CS_MOVE::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CS_MOVE* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "CS_MOVE"; }

  explicit CS_MOVE(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CS_MOVE(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CS_MOVE& from);
  CS_MOVE(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CS_MOVE&& from) noexcept
      : CS_MOVE(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kMoveTimeFieldNumber = 2,
    kDirFieldNumber = 1,
  };
  // int64 move_time = 2;
  void clear_move_time() ;
  ::int64_t move_time() const;
  void set_move_time(::int64_t value);

  private:
  ::int64_t _internal_move_time() const;
  void _internal_set_move_time(::int64_t value);

  public:
  // .Direction dir = 1;
  void clear_dir() ;
  ::Direction dir() const;
  void set_dir(::Direction value);

  private:
  ::Direction _internal_dir() const;
  void _internal_set_dir(::Direction value);

  public:
  // @@protoc_insertion_point(class_scope:CS_MOVE)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CS_MOVE& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int64_t move_time_;
    int dir_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_protocol_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CS_MOVE_class_data_;
// -------------------------------------------------------------------

class CS_LOGIN final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:CS_LOGIN) */ {
 public:
  inline CS_LOGIN() : CS_LOGIN(nullptr) {}
  ~CS_LOGIN() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CS_LOGIN* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CS_LOGIN));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CS_LOGIN(::google::protobuf::internal::ConstantInitialized);

  inline CS_LOGIN(const CS_LOGIN& from) : CS_LOGIN(nullptr, from) {}
  inline CS_LOGIN(CS_LOGIN&& from) noexcept
      : CS_LOGIN(nullptr, ::std::move(from)) {}
  inline CS_LOGIN& operator=(const CS_LOGIN& from) {
    CopyFrom(from);
    return *this;
  }
  inline CS_LOGIN& operator=(CS_LOGIN&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CS_LOGIN& default_instance() {
    return *reinterpret_cast<const CS_LOGIN*>(
        &_CS_LOGIN_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(CS_LOGIN& a, CS_LOGIN& b) { a.Swap(&b); }
  inline void Swap(CS_LOGIN* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CS_LOGIN* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CS_LOGIN* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CS_LOGIN>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CS_LOGIN& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CS_LOGIN& from) { CS_LOGIN::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CS_LOGIN* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "CS_LOGIN"; }

  explicit CS_LOGIN(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CS_LOGIN(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CS_LOGIN& from);
  CS_LOGIN(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CS_LOGIN&& from) noexcept
      : CS_LOGIN(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kUserNameFieldNumber = 1,
  };
  // string user_name = 1;
  void clear_user_name() ;
  const ::std::string& user_name() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_user_name(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_user_name();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_user_name();
  void set_allocated_user_name(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_user_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_user_name(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_user_name();

  public:
  // @@protoc_insertion_point(class_scope:CS_LOGIN)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 26,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CS_LOGIN& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr user_name_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_protocol_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CS_LOGIN_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// SC_LOGIN_OK

// int32 id = 1;
inline void SC_LOGIN_OK::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::int32_t SC_LOGIN_OK::id() const {
  // @@protoc_insertion_point(field_get:SC_LOGIN_OK.id)
  return _internal_id();
}
inline void SC_LOGIN_OK::set_id(::int32_t value) {
  _internal_set_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:SC_LOGIN_OK.id)
}
inline ::int32_t SC_LOGIN_OK::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_;
}
inline void SC_LOGIN_OK::_internal_set_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = value;
}

// int32 x = 2;
inline void SC_LOGIN_OK::clear_x() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::int32_t SC_LOGIN_OK::x() const {
  // @@protoc_insertion_point(field_get:SC_LOGIN_OK.x)
  return _internal_x();
}
inline void SC_LOGIN_OK::set_x(::int32_t value) {
  _internal_set_x(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:SC_LOGIN_OK.x)
}
inline ::int32_t SC_LOGIN_OK::_internal_x() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.x_;
}
inline void SC_LOGIN_OK::_internal_set_x(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = value;
}

// int32 y = 3;
inline void SC_LOGIN_OK::clear_y() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::int32_t SC_LOGIN_OK::y() const {
  // @@protoc_insertion_point(field_get:SC_LOGIN_OK.y)
  return _internal_y();
}
inline void SC_LOGIN_OK::set_y(::int32_t value) {
  _internal_set_y(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:SC_LOGIN_OK.y)
}
inline ::int32_t SC_LOGIN_OK::_internal_y() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.y_;
}
inline void SC_LOGIN_OK::_internal_set_y(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = value;
}

// -------------------------------------------------------------------

// SC_POS

// int32 id = 1;
inline void SC_POS::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::int32_t SC_POS::id() const {
  // @@protoc_insertion_point(field_get:SC_POS.id)
  return _internal_id();
}
inline void SC_POS::set_id(::int32_t value) {
  _internal_set_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:SC_POS.id)
}
inline ::int32_t SC_POS::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_;
}
inline void SC_POS::_internal_set_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = value;
}

// int32 x = 2;
inline void SC_POS::clear_x() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::int32_t SC_POS::x() const {
  // @@protoc_insertion_point(field_get:SC_POS.x)
  return _internal_x();
}
inline void SC_POS::set_x(::int32_t value) {
  _internal_set_x(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:SC_POS.x)
}
inline ::int32_t SC_POS::_internal_x() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.x_;
}
inline void SC_POS::_internal_set_x(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = value;
}

// int32 y = 3;
inline void SC_POS::clear_y() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::int32_t SC_POS::y() const {
  // @@protoc_insertion_point(field_get:SC_POS.y)
  return _internal_y();
}
inline void SC_POS::set_y(::int32_t value) {
  _internal_set_y(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:SC_POS.y)
}
inline ::int32_t SC_POS::_internal_y() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.y_;
}
inline void SC_POS::_internal_set_y(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = value;
}

// int64 move_time = 4;
inline void SC_POS::clear_move_time() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.move_time_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::int64_t SC_POS::move_time() const {
  // @@protoc_insertion_point(field_get:SC_POS.move_time)
  return _internal_move_time();
}
inline void SC_POS::set_move_time(::int64_t value) {
  _internal_set_move_time(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:SC_POS.move_time)
}
inline ::int64_t SC_POS::_internal_move_time() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.move_time_;
}
inline void SC_POS::_internal_set_move_time(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.move_time_ = value;
}

// -------------------------------------------------------------------

// SC_PUT_OBJECT

// int32 id = 1;
inline void SC_PUT_OBJECT::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::int32_t SC_PUT_OBJECT::id() const {
  // @@protoc_insertion_point(field_get:SC_PUT_OBJECT.id)
  return _internal_id();
}
inline void SC_PUT_OBJECT::set_id(::int32_t value) {
  _internal_set_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:SC_PUT_OBJECT.id)
}
inline ::int32_t SC_PUT_OBJECT::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_;
}
inline void SC_PUT_OBJECT::_internal_set_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = value;
}

// int32 x = 2;
inline void SC_PUT_OBJECT::clear_x() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::int32_t SC_PUT_OBJECT::x() const {
  // @@protoc_insertion_point(field_get:SC_PUT_OBJECT.x)
  return _internal_x();
}
inline void SC_PUT_OBJECT::set_x(::int32_t value) {
  _internal_set_x(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:SC_PUT_OBJECT.x)
}
inline ::int32_t SC_PUT_OBJECT::_internal_x() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.x_;
}
inline void SC_PUT_OBJECT::_internal_set_x(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = value;
}

// int32 y = 3;
inline void SC_PUT_OBJECT::clear_y() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::int32_t SC_PUT_OBJECT::y() const {
  // @@protoc_insertion_point(field_get:SC_PUT_OBJECT.y)
  return _internal_y();
}
inline void SC_PUT_OBJECT::set_y(::int32_t value) {
  _internal_set_y(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:SC_PUT_OBJECT.y)
}
inline ::int32_t SC_PUT_OBJECT::_internal_y() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.y_;
}
inline void SC_PUT_OBJECT::_internal_set_y(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = value;
}

// int32 o_type = 4;
inline void SC_PUT_OBJECT::clear_o_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.o_type_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::int32_t SC_PUT_OBJECT::o_type() const {
  // @@protoc_insertion_point(field_get:SC_PUT_OBJECT.o_type)
  return _internal_o_type();
}
inline void SC_PUT_OBJECT::set_o_type(::int32_t value) {
  _internal_set_o_type(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:SC_PUT_OBJECT.o_type)
}
inline ::int32_t SC_PUT_OBJECT::_internal_o_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.o_type_;
}
inline void SC_PUT_OBJECT::_internal_set_o_type(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.o_type_ = value;
}

// -------------------------------------------------------------------

// SC_REMOVE_OBJECT

// int32 id = 1;
inline void SC_REMOVE_OBJECT::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::int32_t SC_REMOVE_OBJECT::id() const {
  // @@protoc_insertion_point(field_get:SC_REMOVE_OBJECT.id)
  return _internal_id();
}
inline void SC_REMOVE_OBJECT::set_id(::int32_t value) {
  _internal_set_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:SC_REMOVE_OBJECT.id)
}
inline ::int32_t SC_REMOVE_OBJECT::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_;
}
inline void SC_REMOVE_OBJECT::_internal_set_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = value;
}

// -------------------------------------------------------------------

// CS_LOGIN

// string user_name = 1;
inline void CS_LOGIN::clear_user_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.user_name_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& CS_LOGIN::user_name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:CS_LOGIN.user_name)
  return _internal_user_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void CS_LOGIN::set_user_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.user_name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:CS_LOGIN.user_name)
}
inline ::std::string* PROTOBUF_NONNULL CS_LOGIN::mutable_user_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_user_name();
  // @@protoc_insertion_point(field_mutable:CS_LOGIN.user_name)
  return _s;
}
inline const ::std::string& CS_LOGIN::_internal_user_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.user_name_.Get();
}
inline void CS_LOGIN::_internal_set_user_name(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.user_name_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL CS_LOGIN::_internal_mutable_user_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.user_name_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE CS_LOGIN::release_user_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:CS_LOGIN.user_name)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.user_name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.user_name_.Set("", GetArena());
  }
  return released;
}
inline void CS_LOGIN::set_allocated_user_name(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.user_name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.user_name_.IsDefault()) {
    _impl_.user_name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:CS_LOGIN.user_name)
}

// -------------------------------------------------------------------

// CS_MOVE

// .Direction dir = 1;
inline void CS_MOVE::clear_dir() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dir_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::Direction CS_MOVE::dir() const {
  // @@protoc_insertion_point(field_get:CS_MOVE.dir)
  return _internal_dir();
}
inline void CS_MOVE::set_dir(::Direction value) {
  _internal_set_dir(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:CS_MOVE.dir)
}
inline ::Direction CS_MOVE::_internal_dir() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::Direction>(_impl_.dir_);
}
inline void CS_MOVE::_internal_set_dir(::Direction value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dir_ = value;
}

// int64 move_time = 2;
inline void CS_MOVE::clear_move_time() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.move_time_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::int64_t CS_MOVE::move_time() const {
  // @@protoc_insertion_point(field_get:CS_MOVE.move_time)
  return _internal_move_time();
}
inline void CS_MOVE::set_move_time(::int64_t value) {
  _internal_set_move_time(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:CS_MOVE.move_time)
}
inline ::int64_t CS_MOVE::_internal_move_time() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.move_time_;
}
inline void CS_MOVE::_internal_set_move_time(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.move_time_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::Direction> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::Direction>() {
  return ::Direction_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // protocol_2eproto_2epb_2eh
