// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PROTOCOL_H_
#define FLATBUFFERS_GENERATED_PROTOCOL_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

struct Message_C2S;
struct Message_C2SBuilder;

struct Message_S2C;
struct Message_S2CBuilder;

enum PACKET_TYPE : uint8_t {
  PACKET_TYPE_MESSAGE_C2S = 100,
  PACKET_TYPE_MESSAGE_S2C = 101,
  PACKET_TYPE_MIN = PACKET_TYPE_MESSAGE_C2S,
  PACKET_TYPE_MAX = PACKET_TYPE_MESSAGE_S2C
};

inline const PACKET_TYPE (&EnumValuesPACKET_TYPE())[2] {
  static const PACKET_TYPE values[] = {
    PACKET_TYPE_MESSAGE_C2S,
    PACKET_TYPE_MESSAGE_S2C
  };
  return values;
}

inline const char * const *EnumNamesPACKET_TYPE() {
  static const char * const names[3] = {
    "MESSAGE_C2S",
    "MESSAGE_S2C",
    nullptr
  };
  return names;
}

inline const char *EnumNamePACKET_TYPE(PACKET_TYPE e) {
  if (::flatbuffers::IsOutRange(e, PACKET_TYPE_MESSAGE_C2S, PACKET_TYPE_MESSAGE_S2C)) return "";
  const size_t index = static_cast<size_t>(e) - static_cast<size_t>(PACKET_TYPE_MESSAGE_C2S);
  return EnumNamesPACKET_TYPE()[index];
}

struct Message_C2S FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Message_C2SBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MSG = 4
  };
  const ::flatbuffers::String *msg() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MSG);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_MSG) &&
           verifier.VerifyString(msg()) &&
           verifier.EndTable();
  }
};

struct Message_C2SBuilder {
  typedef Message_C2S Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_msg(::flatbuffers::Offset<::flatbuffers::String> msg) {
    fbb_.AddOffset(Message_C2S::VT_MSG, msg);
  }
  explicit Message_C2SBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Message_C2S> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Message_C2S>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Message_C2S> CreateMessage_C2S(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> msg = 0) {
  Message_C2SBuilder builder_(_fbb);
  builder_.add_msg(msg);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Message_C2S> CreateMessage_C2SDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *msg = nullptr) {
  auto msg__ = msg ? _fbb.CreateString(msg) : 0;
  return CreateMessage_C2S(
      _fbb,
      msg__);
}

struct Message_S2C FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Message_S2CBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SEQ = 4,
    VT_MSG = 6
  };
  int32_t seq() const {
    return GetField<int32_t>(VT_SEQ, 0);
  }
  const ::flatbuffers::String *msg() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MSG);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_SEQ, 4) &&
           VerifyOffset(verifier, VT_MSG) &&
           verifier.VerifyString(msg()) &&
           verifier.EndTable();
  }
};

struct Message_S2CBuilder {
  typedef Message_S2C Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_seq(int32_t seq) {
    fbb_.AddElement<int32_t>(Message_S2C::VT_SEQ, seq, 0);
  }
  void add_msg(::flatbuffers::Offset<::flatbuffers::String> msg) {
    fbb_.AddOffset(Message_S2C::VT_MSG, msg);
  }
  explicit Message_S2CBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Message_S2C> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Message_S2C>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Message_S2C> CreateMessage_S2C(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t seq = 0,
    ::flatbuffers::Offset<::flatbuffers::String> msg = 0) {
  Message_S2CBuilder builder_(_fbb);
  builder_.add_msg(msg);
  builder_.add_seq(seq);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Message_S2C> CreateMessage_S2CDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t seq = 0,
    const char *msg = nullptr) {
  auto msg__ = msg ? _fbb.CreateString(msg) : 0;
  return CreateMessage_S2C(
      _fbb,
      seq,
      msg__);
}

#endif  // FLATBUFFERS_GENERATED_PROTOCOL_H_
